function systems:context/air/mainstart
function systems:context/attackhit/mainstart
function systems:context/crouch/mainstart
function systems:context/fall/mainstart
function systems:context/ground/mainstart
function systems:context/hurt/mainstart
function systems:context/jump/mainstart
function systems:context/rcd/mainstart
function systems:context/sneak/mainstart
function systems:context/sprint/mainstart
function systems:context/walk/mainstart
