# function entity:testenemy/sequences/stunned if @s[score_sequenceSelect_min=1,score_sequenceSelect=1]
function entity:slasher/sequences/strafe if @s[score_sequenceSelect_min=10,score_sequenceSelect=10]
function entity:slasher/sequences/slash1 if @s[score_sequenceSelect_min=20,score_sequenceSelect=20]
function entity:slasher/sequences/slash2 if @s[score_sequenceSelect_min=21,score_sequenceSelect=21]
function entity:slasher/sequences/slash3 if @s[score_sequenceSelect_min=22,score_sequenceSelect=22]
function entity:slasher/sequences/slash4 if @s[score_sequenceSelect_min=23,score_sequenceSelect=23]
function entity:slasher/sequences/slashOverhead if @s[score_sequenceSelect_min=25,score_sequenceSelect=25]
function entity:slasher/sequences/slashCombo1 if @s[score_sequenceSelect_min=30,score_sequenceSelect=30]
function entity:slasher/sequences/slashCombo2 if @s[score_sequenceSelect_min=31,score_sequenceSelect=31]
